import type { Apartment } from "./types";

const img = (id: string, w = 1400) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

// Dữ liệu mẫu dùng khi chưa cấu hình Supabase - đủ để xem toàn bộ giao diện.
export const MOCK_APARTMENTS: Apartment[] = [
  {
    id: "a1",
    slug: "the-kyoto-k1-2208-view-ho",
    owner_id: "o1",
    name: "Kyoto Skyline Residence",
    code: "K1-2208",
    subzone: "The Kyoto",
    address: "Toà K1, The Kyoto, Vinhomes Star City, TP. Thanh Hoá",
    area: 78,
    bedrooms: 2,
    layout: "2pn",
    bathrooms: 2,
    floor: 22,
    orientation: "Đông Nam",
    price: 18_000_000,
    status: "trong",
    lease_term: "12_thang",
    rating: 4.9,
    description:
      "Căn hộ 2 phòng ngủ tầng cao tại The Kyoto, tầm nhìn trọn vẹn hồ điều hoà trung tâm. Nội thất nhập khẩu phong cách Nhật Bản tối giản, ban công rộng đón nắng sớm.",
    has_ai_tour: true,
    created_at: "2026-05-20T08:00:00Z",
    cover_url: img("photo-1502672260266-1c1ef2d93688"),
    media: [
      { id: "m1", apartment_id: "a1", url: img("photo-1502672260266-1c1ef2d93688"), type: "anh", sort_order: 1, alt: "Phòng khách Kyoto Skyline" },
      { id: "m2", apartment_id: "a1", url: img("photo-1493809842364-78817add7ffb"), type: "anh", sort_order: 2, alt: "Khu vực sofa" },
      { id: "m3", apartment_id: "a1", url: img("photo-1505693416388-ac5ce068fe85"), type: "anh", sort_order: 3, alt: "Phòng ngủ chính" },
      { id: "m4", apartment_id: "a1", url: img("photo-1556912172-45b7abe8b7e1"), type: "anh", sort_order: 4, alt: "Khu bếp" },
      { id: "mv1", apartment_id: "a1", url: "", type: "ai_tour_video", sort_order: 5, alt: "AI Video Tour" },
    ],
    amenities: [
      { id: "am1", apartment_id: "a1", name: "View hồ trung tâm", icon: "eye" },
      { id: "am2", apartment_id: "a1", name: "Hồ bơi vô cực", icon: "waves" },
      { id: "am3", apartment_id: "a1", name: "Phòng gym", icon: "dumbbell" },
      { id: "am4", apartment_id: "a1", name: "Ban công rộng", icon: "sun" },
      { id: "am5", apartment_id: "a1", name: "Bãi đỗ xe", icon: "car" },
      { id: "am6", apartment_id: "a1", name: "An ninh 24/7", icon: "shield" },
      { id: "am7", apartment_id: "a1", name: "Nội thất cao cấp", icon: "sofa" },
      { id: "am8", apartment_id: "a1", name: "Smart home", icon: "smartphone" },
    ],
  },
  {
    id: "a2",
    slug: "the-sentosa-s5-1505-3pn",
    owner_id: "o1",
    name: "Sentosa Garden Suite",
    code: "S5-1505",
    subzone: "The Sentosa",
    address: "Toà S5, The Sentosa, Vinhomes Star City, TP. Thanh Hoá",
    area: 102,
    bedrooms: 3,
    layout: "3pn",
    bathrooms: 2,
    floor: 15,
    orientation: "Tây Nam",
    price: 26_000_000,
    status: "trong",
    lease_term: "12_thang",
    rating: 4.8,
    description:
      "Căn góc 3 phòng ngủ thoáng hai mặt, ngập tràn ánh sáng tự nhiên. Thiết kế tân cổ điển sang trọng, phù hợp gia đình. Liền kề công viên trung tâm và khu shophouse.",
    has_ai_tour: true,
    created_at: "2026-05-28T08:00:00Z",
    cover_url: img("photo-1560448204-e02f11c3d0e2"),
    media: [
      { id: "m5", apartment_id: "a2", url: img("photo-1560448204-e02f11c3d0e2"), type: "anh", sort_order: 1, alt: "Phòng khách Sentosa" },
      { id: "m6", apartment_id: "a2", url: img("photo-1522708323590-d24dbb6b0267"), type: "anh", sort_order: 2, alt: "Không gian sinh hoạt chung" },
      { id: "m7", apartment_id: "a2", url: img("photo-1505693416388-ac5ce068fe85"), type: "anh", sort_order: 3, alt: "Phòng ngủ" },
    ],
    amenities: [
      { id: "am9", apartment_id: "a2", name: "Căn góc 2 view", icon: "eye" },
      { id: "am10", apartment_id: "a2", name: "Hồ bơi", icon: "waves" },
      { id: "am11", apartment_id: "a2", name: "Phòng gym", icon: "dumbbell" },
      { id: "am12", apartment_id: "a2", name: "Bãi đỗ xe", icon: "car" },
      { id: "am13", apartment_id: "a2", name: "An ninh 24/7", icon: "shield" },
      { id: "am14", apartment_id: "a2", name: "Bếp đầy đủ", icon: "utensils" },
    ],
  },
  {
    id: "a3",
    slug: "the-sentosa-s2-0810-studio",
    owner_id: "o2",
    name: "Sentosa Lakeview Studio",
    code: "S2-0810",
    subzone: "The Sentosa",
    address: "Toà S2, The Sentosa, Vinhomes Star City, TP. Thanh Hoá",
    area: 45,
    bedrooms: 1,
    layout: "studio",
    bathrooms: 1,
    floor: 8,
    orientation: "Đông",
    price: 11_500_000,
    status: "trong",
    lease_term: "ngan_han",
    rating: 4.7,
    description:
      "Studio hiện đại đầy đủ nội thất, lý tưởng cho chuyên gia và người độc thân. Bàn giao tinh tế, view hồ Sentosa, đi bộ 3 phút tới tiện ích khối đế.",
    has_ai_tour: true,
    created_at: "2026-06-02T08:00:00Z",
    cover_url: img("photo-1540518614846-7eded433c457"),
    media: [
      { id: "m8", apartment_id: "a3", url: img("photo-1540518614846-7eded433c457"), type: "anh", sort_order: 1, alt: "Studio Sentosa" },
      { id: "m9", apartment_id: "a3", url: img("photo-1493809842364-78817add7ffb"), type: "anh", sort_order: 2, alt: "Khu tiếp khách" },
    ],
    amenities: [
      { id: "am15", apartment_id: "a3", name: "View hồ Sentosa", icon: "eye" },
      { id: "am16", apartment_id: "a3", name: "Hồ bơi", icon: "waves" },
      { id: "am17", apartment_id: "a3", name: "Máy giặt", icon: "washing" },
      { id: "am18", apartment_id: "a3", name: "Điều hoà", icon: "air" },
      { id: "am19", apartment_id: "a3", name: "An ninh 24/7", icon: "shield" },
    ],
  },
  {
    id: "a4",
    slug: "the-k-park-avenue-kp1-1802-3pn",
    owner_id: "o2",
    name: "K-Park Avenue Premier",
    code: "KP1-1802",
    subzone: "The K-Park Avenue",
    address: "Toà KP1, The K-Park Avenue, Vinhomes Star City, TP. Thanh Hoá",
    area: 115,
    bedrooms: 3,
    layout: "3pn",
    bathrooms: 3,
    floor: 18,
    orientation: "Nam",
    price: 32_000_000,
    status: "dang_thue",
    lease_term: "24_thang",
    rating: 5.0,
    description:
      "Căn hộ cao cấp nhất phân khu K-Park Avenue, 3 phòng ngủ master en-suite. Nội thất dát đồng, hệ thống smart home toàn bộ, view quảng trường ánh sáng.",
    has_ai_tour: true,
    created_at: "2026-04-15T08:00:00Z",
    cover_url: img("photo-1600210492486-724fe5c67fb0"),
    media: [
      { id: "m10", apartment_id: "a4", url: img("photo-1600210492486-724fe5c67fb0"), type: "anh", sort_order: 1, alt: "K-Park Premier" },
      { id: "m11", apartment_id: "a4", url: img("photo-1600607687939-ce8a6c25118c"), type: "anh", sort_order: 2, alt: "Phòng khách lớn" },
      { id: "m12", apartment_id: "a4", url: img("photo-1600566753086-00f18fb6b3ea"), type: "anh", sort_order: 3, alt: "Phòng ngủ master" },
    ],
    amenities: [
      { id: "am20", apartment_id: "a4", name: "Smart home toàn bộ", icon: "smartphone" },
      { id: "am21", apartment_id: "a4", name: "Hồ bơi vô cực", icon: "waves" },
      { id: "am22", apartment_id: "a4", name: "Phòng gym", icon: "dumbbell" },
      { id: "am23", apartment_id: "a4", name: "2 chỗ đỗ xe", icon: "car" },
      { id: "am24", apartment_id: "a4", name: "An ninh 24/7", icon: "shield" },
      { id: "am25", apartment_id: "a4", name: "Nội thất cao cấp", icon: "sofa" },
    ],
  },
  {
    id: "a5",
    slug: "the-kyoto-k2-1102-2pn-noi-that",
    owner_id: "o1",
    name: "Kyoto Zen Apartment",
    code: "K2-1102",
    subzone: "The Kyoto",
    address: "Toà K2, The Kyoto, Vinhomes Star City, TP. Thanh Hoá",
    area: 72,
    bedrooms: 2,
    layout: "2pn+1",
    bathrooms: 2,
    floor: 11,
    orientation: "Đông Bắc",
    price: 16_500_000,
    status: "trong",
    lease_term: "12_thang",
    rating: 4.6,
    description:
      "Căn 2 phòng ngủ phong cách Zen Nhật Bản, gỗ sồi tự nhiên và tông màu trầm ấm. Bàn giao full nội thất, dọn vào ở ngay.",
    has_ai_tour: false,
    created_at: "2026-06-08T08:00:00Z",
    cover_url: img("photo-1600585154526-990dced4db0d"),
    media: [
      { id: "m13", apartment_id: "a5", url: img("photo-1600585154526-990dced4db0d"), type: "anh", sort_order: 1, alt: "Kyoto Zen" },
      { id: "m14", apartment_id: "a5", url: img("photo-1556912172-45b7abe8b7e1"), type: "anh", sort_order: 2, alt: "Khu bếp" },
    ],
    amenities: [
      { id: "am26", apartment_id: "a5", name: "Hồ bơi", icon: "waves" },
      { id: "am27", apartment_id: "a5", name: "Ban công", icon: "sun" },
      { id: "am28", apartment_id: "a5", name: "Bãi đỗ xe", icon: "car" },
      { id: "am29", apartment_id: "a5", name: "An ninh 24/7", icon: "shield" },
      { id: "am30", apartment_id: "a5", name: "Nội thất cao cấp", icon: "sofa" },
    ],
  },
  {
    id: "a6",
    slug: "the-k-park-avenue-kp3-2010-1pn1",
    owner_id: "o2",
    name: "K-Park Avenue Sky Residence",
    code: "KP3-2010",
    subzone: "The K-Park Avenue",
    address: "Toà KP3, The K-Park Avenue, Vinhomes Star City, TP. Thanh Hoá",
    area: 85,
    bedrooms: 2,
    layout: "1pn+1",
    bathrooms: 2,
    floor: 20,
    orientation: "Tây",
    price: 21_000_000,
    status: "trong",
    lease_term: "12_thang",
    rating: 4.8,
    description:
      "Căn hộ tầng cao đón hoàng hôn rực rỡ trên hồ. Phong cách Indochine hiện đại, ban công rộng, phù hợp cặp đôi và gia đình trẻ.",
    has_ai_tour: true,
    created_at: "2026-06-10T08:00:00Z",
    cover_url: img("photo-1600121848594-d8644e57abab"),
    media: [
      { id: "m15", apartment_id: "a6", url: img("photo-1600121848594-d8644e57abab"), type: "anh", sort_order: 1, alt: "K-Park Avenue Sky" },
      { id: "m16", apartment_id: "a6", url: img("photo-1493809842364-78817add7ffb"), type: "anh", sort_order: 2, alt: "Phòng khách" },
    ],
    amenities: [
      { id: "am31", apartment_id: "a6", name: "View hoàng hôn", icon: "eye" },
      { id: "am32", apartment_id: "a6", name: "Hồ bơi", icon: "waves" },
      { id: "am33", apartment_id: "a6", name: "Phòng gym", icon: "dumbbell" },
      { id: "am34", apartment_id: "a6", name: "Ban công rộng", icon: "sun" },
      { id: "am35", apartment_id: "a6", name: "An ninh 24/7", icon: "shield" },
    ],
  },
];

export interface Testimonial {
  id: string;
  name: string;
  role: string;
  avatar: string;
  rating: number;
  quote: string;
}

export const MOCK_TESTIMONIALS: Testimonial[] = [
  {
    id: "t1",
    name: "Nguyễn Minh Anh",
    role: "Khách thuê · The Kyoto",
    avatar: img("photo-1494790108377-be9c29b29330", 200),
    rating: 5,
    quote:
      "AI Video Tour giúp tôi chọn được căn ưng ý mà không cần đi lại nhiều lần. Đội ngũ phản hồi cực nhanh, thủ tục minh bạch, rõ ràng.",
  },
  {
    id: "t2",
    name: "Trần Quốc Bảo",
    role: "Chủ nhà · 4 căn cho thuê",
    avatar: img("photo-1507003211169-0a1dd7228f2d", 200),
    rating: 5,
    quote:
      "Tôi giao toàn bộ việc cho thuê cho CanHoXuThanh. Tỷ lệ lấp đầy gần như tuyệt đối, báo cáo doanh thu rõ ràng từng tháng. Rất yên tâm.",
  },
  {
    id: "t3",
    name: "Lê Thuỳ Dương",
    role: "Khách thuê · The Victoria",
    avatar: img("photo-1438761681033-6461ffad8d80", 200),
    rating: 5,
    quote:
      "Căn hộ đúng như hình, đúng như tour ảo. Hỗ trợ pháp lý chu đáo, ký hợp đồng nhanh gọn. Trải nghiệm xứng tầm Vinhomes.",
  },
];
